spring:
  application:
    name: service-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: customer-ribbon
    api-b:
      path: /api-b/**
      serviceId: customer-feign

